// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/checklist/CardsView.tsx": () => import("../components/mockups/checklist/CardsView.tsx"),
  "./components/mockups/checklist/TabelaView.tsx": () => import("../components/mockups/checklist/TabelaView.tsx")
};
